# WARNING:
## DO NOT commit *settings.yaml* file

settings:

  #### Server connection
  server:

    #### (String) Server IP
    ip: 127.0.0.1

    #### (u32) Server port
    port: 5050

    #### (String) Domain name
    domain: http://127.0.0.1

    #### (String) Cookie secret `openssl rand -base64 128`
    cookie_secret: XXXXXXXXXXXXXXX

    #### (i64) max age of the cookie
    cookie_max_age_secs: 216000

    # (String) api secret token `openssl rand -base64 64`
    api_secret_token: XXXXXXXXXXXXXXX

    # (String) API secret token key which has to be passed via API header
    api_secret_key: "API_TOKEN_XXX"

    #### (bool) http available
    https: false
